/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AwesomeCards {
    'columns': string;
    'gap': string;
    'rows': string;
    'setGridColumns': () => Promise<void>;
    'setGridGap': () => Promise<void>;
  }
}

declare global {


  interface HTMLAwesomeCardsElement extends Components.AwesomeCards, HTMLStencilElement {}
  var HTMLAwesomeCardsElement: {
    prototype: HTMLAwesomeCardsElement;
    new (): HTMLAwesomeCardsElement;
  };
  interface HTMLElementTagNameMap {
    'awesome-cards': HTMLAwesomeCardsElement;
  }
}

declare namespace LocalJSX {
  interface AwesomeCards {
    'columns'?: string;
    'gap'?: string;
    'rows'?: string;
  }

  interface IntrinsicElements {
    'awesome-cards': AwesomeCards;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'awesome-cards': LocalJSX.AwesomeCards & JSXBase.HTMLAttributes<HTMLAwesomeCardsElement>;
    }
  }
}


